NikitaBlog/Models/Category.cs
using System.ComponentModel.DataAnnotations;

namespace NikitaBlog.Models
{
    public class Category
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [MaxLength(25)]
        public string Title { get; set; } = null!;

        public int DisplayOrder { get; set; }

    }
}

NikitaBlog/Models/ErrorViewModel.cs
namespace NikitaBlog.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

NikitaBlog/Models/Post.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace NikitaBlog.Models
{
    public class Post
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [MaxLength(50)]
        public string Title { get; set; } = null!;

        [Required]
        [MaxLength(50)]
        public string Author { get; set; } = null!;

        [Required]
        [MaxLength(5000)]
        public string Text { get; set; } = null!;

        [ForeignKey("CategoryId")]
        [ValidateNever]
        public Category Category { get; set; }
        public int CategoryId { get; set; }

        public string? ImageUrl { get; set; }



    }
}

NikitaBlog/Models/PostVM.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace NikitaBlog.Models
{
    public class PostVM
    {
        public Post Post { get; set; }

        [ValidateNever]
        public IEnumerable<SelectListItem> CategoryList { get; set; }
    }
}

NikitaBlog/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using NikitaBlog.Models;
using NikitaBlog.Repository.IRepository;
using System.Security.Permissions;

namespace NikitaBlog.Controllers
{
    public class CategoryController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public CategoryController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            List<Category> categories = _unitOfWork.Category.GetAll().ToList();
            return View(categories);
        }

        public IActionResult Upsert(int? id)
        {
            if(id is null || id == 0)
            {
                Category category = new();
                return View(category);
            }
            else
            {
                Category? category = _unitOfWork.Category.Get(c => c.Id == id);
                return View(category);
            }
        }

        [HttpPost]
        public IActionResult Upsert(Category category)
        {
            if (!ModelState.IsValid)
            {
                return View(category);
            }

            if(category.Id == 0)
            {
                _unitOfWork.Category.Add(category);
                _unitOfWork.Save();
                TempData["success"] = $"Catery {category.Title} added";
            }
            else
            {
                _unitOfWork.Category.Update(category);
                _unitOfWork.Save();
                TempData["success"] = $"Catery {category.Title} updated";
            }

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Delete(int id)
        {
            Category? category = _unitOfWork.Category.Get(c => c.Id == id);
            return View(category);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteAction(int id)
        {
            Category? category = _unitOfWork.Category.Get(c => c.Id == id);
            if(category is null)
            {
                return NotFound();
            }

            _unitOfWork.Category.Remove(category);
            _unitOfWork.Save();
            TempData["success"] = $"Catery {category.Title} deleted";

            return RedirectToAction(nameof(Index));
        }
        
    }
}

NikitaBlog/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using NikitaBlog.Data;
using NikitaBlog.Models;
using System.Diagnostics;

namespace NikitaBlog.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationDbContext _context;

        public HomeController(ILogger<HomeController> logger, ApplicationDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

NikitaBlog/Controllers/PostController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Formatters;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NikitaBlog.Data;
using NikitaBlog.Models;
using NikitaBlog.Repository.IRepository;

namespace NikitaBlog.Controllers
{
    public class PostController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public PostController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
        }

        public IActionResult Index()
        {
            List<Post> posts = _unitOfWork.Post.GetAll().ToList();
            
            return View(posts);
        }

        public IActionResult Details(int id)
        {
            Post? post = _unitOfWork.Post.Get(p => p.Id == id);
            return View(post);
        }

        public IActionResult Upsert(int? id)
        {
            IEnumerable<SelectListItem> CategoryList = _unitOfWork.Category.GetAll().Select(c => new SelectListItem
            {
                Text = c.Title,
                Value = c.Id.ToString()
            });

            PostVM postVM = new()
            {
                Post = new Post(),
                CategoryList = CategoryList
            };

            if (id is null || id == 0)
            {
                return View(postVM);
            }
            else
            {
                postVM.Post = _unitOfWork.Post.Get(post => post.Id == id);
                return View(postVM);
            }
        }

        [HttpPost]
        public IActionResult Upsert(PostVM postVM, IFormFile? file)
        {
            if (!ModelState.IsValid)
            {
                postVM.CategoryList = _unitOfWork.Category.GetAll().Select(c => new SelectListItem
                {
                    Text = c.Title,
                    Value = c.Id.ToString()
                });
            }

            string wwwRootPath = _webHostEnvironment.WebRootPath;
            if(file is not null)
            {
                string postPath = Path.Combine(wwwRootPath, $@"images\posts");
                string fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);

                using (FileStream fileStream = new FileStream(Path.Combine(postPath, fileName), FileMode.Create))
                {
                    file.CopyTo(fileStream);
                }

                postVM.Post.ImageUrl = @"\images\posts\" + fileName;
            }

            if(postVM.Post.Id == 0)
            {
                //create
                _unitOfWork.Post.Add(postVM.Post);
                _unitOfWork.Save();
                TempData["success"] = $"Post {postVM.Post.Title} created";
            }
            else
            {
                //update
                _unitOfWork.Post.Update(postVM.Post);
                _unitOfWork.Save();
                TempData["success"] = $"Post {postVM.Post.Title} updated";

            }

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Delete(int id)
        {
            Post? post = _unitOfWork.Post.Get(p => p.Id == id);
            return View(post);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteAction(int id)
        {
            Post? post = _unitOfWork.Post.Get(p => p.Id == id);

            _unitOfWork.Post.Remove(post);
            _unitOfWork.Save();

            return RedirectToAction(nameof(Index));
        }

    
    }
}

NikitaBlog/Views/Category/Delete.cshtml
@model Category
@{
    ViewData["Title"] = "Delete";
}

<div class="container">

    <div class="row">
        <h2 class="text-primary">Are you sure you want to delete this category</h2>
    </div>

    <div class="row">
        <form asp-action="Delete" method="post">
            <input asp-for="Id" hidden />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="@Model.Title" class="control-label"></label>
                <input asp-for="@Model.Title" disabled class="form-control" />
                <span asp-validation-for="@Model.Title" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="@Model.DisplayOrder" class="control-label"></label>
                <input asp-for="@Model.DisplayOrder" disabled class="form-control" />
                <span asp-validation-for="@Model.DisplayOrder" class="text-danger"></span>
            </div>

            <div class="row justify-content-center">

                <div class="form-group col-6">
                    <button type="submit" value="Id" class="btn btn-primary"> Delete</button>
                </div>
                <div class="form-group col-6 text-end">
                    <a asp-action="Index" class="btn btn-primary">Back to List</a>
                </div>

            </div>
        </form>
    </div>
</div>

NikitaBlog/Views/Category/Index.cshtml
@model List<Category>
@{
    ViewData["Title"] = "Index";
}

<div class="container">
   
    <partial name="_Notification" />

    <div class="row">
        <div class="col-6">
            <h2 class="text-primary">Categories</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Category" asp-action="Upsert" class="btn btn-primary">Create</a>
        </div>
    </div>

    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Id</th>
                <td>Title</td>
                <td>Display</td>
                <td></td>
            </tr>
        </thead>
        
        <tbody>
            @foreach(Category category in Model.OrderBy(category => category.DisplayOrder))
            {
                <tr>
                    <td>@category.Id</td>
                    <td>@category.Title</td>
                    <td>@category.DisplayOrder</td>
                    <td class="text-center">
                        <a asp-controller="Category" asp-action="Upsert" asp-route-id="@category.Id" class="btn btn-warning">Edit</a>
                        <a asp-controller="Category" asp-action="Delete" asp-route-id="@category.Id" class="btn btn-danger">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

NikitaBlog/Views/Category/Upsert.cshtml
@model Category
@{
    ViewData["Title"] = "Upsert";
}

<div class="container">

    <div class="row">
        <h2 class="text-primary">@(Model.Id != 0 ? "Update" : "Create") category</h2>
    </div>

    <hr />

    <div class="row">
        <form asp-action="Upsert" method="post">
            <input asp-for="Id" hidden />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="@Model.Title" class="control-label"></label>
                <input asp-for="@Model.Title" class="form-control" />
                <span asp-validation-for="@Model.Title" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="@Model.DisplayOrder" class="control-label"></label>
                <input asp-for="@Model.DisplayOrder" class="form-control" />
                <span asp-validation-for="@Model.DisplayOrder" class="text-danger"></span>
            </div>

            <div class="row justify-content-center">

                <div class="form-group col-6">
                    <button type="submit" class="btn btn-primary"> @(Model.Id != 0 ? "Update" : "Create")</button>
                </div>
                <div class="form-group col-6 text-end">
                    <a asp-action="Index" class="btn btn-primary">Back to List</a>
                </div>

            </div>
        </form>
    </div>

</div>

@section Scripts{
    @{
    <partial name="_ValidationScriptsPartial" />
    }
}

NikitaBlog/Views/Home/Index.cshtml
@model List<Category>
@{
    ViewData["Title"] = "Home Page";
}

<div class="container">
    <div class="row text-center">
        <h2 class="text-primary">Welcome to the Nikita Blog Post App!</h2>
    </div>

    <div class="text-center">
        <a asp-controller="Post" asp-action="Upsert" class=" btn btn-primary">New Post</a>
    </div>

    
</div>

NikitaBlog/Views/Post/Delete.cshtml
@model Post
@{
    ViewData["Title"] = "Delete";
}

<div class="container">
    <div class="row">
        <h2 class="text-primary">Are you sure you want to delete this post? </h2>
    </div>
    <hr />
    <div class="row ">
        <div class="col-8">
            <form asp-action="Delete">
                <input asp-for="Id" hidden />
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Title" class="control-label"></label>
                    <input asp-for="Title" disabled class="form-control" />
                </div>
                <div class="form-group">
                    <label asp-for="Author" class="control-label"></label>
                    <input asp-for="Author" disabled class="form-control" />
                </div>
                <div class="form-group">
                    <label asp-for="Text" class="control-label"></label>
                    <textarea asp-for="Text" disabled class="form-control" rows="10"></textarea>
                </div>
          
                <div class="row justify-content-evenly">
                    <div class="col-md-auto">
                        <button type="submit"  class="btn btn-primary">Delete</button>
                    </div>
                    <div class="col-md-auto">
                        <a asp-action="Index" class="btn btn-primary">Back to List</a>
                    </div>
                </div>
            </form>
        </div>

        <div class="col-4">
            <img src="@Model.ImageUrl" width="300" style="border-radius: 5px; border: 1px solid #bbb9b9" />
        </div>
    </div>



</div>

NikitaBlog/Views/Post/Details.cshtml
@model Post

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div class="text-end">
    <a asp-action="Upsert" asp-route-id="@Model?.Id" class="btn btn-primary">Edit</a> |
    <a asp-action="Index" class="btn btn-primary">Back to List</a>
</div>

<div>
    <h4>Post</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Author)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Text)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Text)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category.Title)
        </dd>
        <dt class = "col-sm-2">
            Image
        </dt>
        <dd class = "col-sm-10 text-center">
           <img src="@Model!.ImageUrl" width="300"/>
        </dd>
    </dl>
</div>

NikitaBlog/Views/Post/Index.cshtml
@model List<Post>
@{
    ViewData["Title"] = "Index";
}

<div class="container">
    <partial name="_Notification" />

    <div class="row">
        <div class="col-10 text-center">
            <h2 class="text-primary">Posts</h2>
        </div>
        <div class="col-2 text-end">
            <a asp-controller="Post" asp-action="Upsert" class="btn btn-primary">Create</a>
        </div>
    </div>

    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Author</th>
                @* <th>Category</th> *@
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach(Post post in Model)
            {
                <tr>
                    <td>@post.Id</td>
                    <td><a asp-controller="Post" asp-action="Details" asp-route-id="@post.Id" class="btn btn-outline-primary">@post.Title</a></td>
                    <td>@post.Author</td>
                    @* <td>@post.Category.Title</td> *@
                    <td class="text-center">
                        <a asp-controller="Post" asp-action="Upsert" asp-route-id="@post.Id" class="btn btn-warning">Edit</a>
                        <a asp-controller="Post" asp-action="Delete" asp-route-id="@post.Id" class="btn btn-danger">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

NikitaBlog/Views/Post/Upsert.cshtml
@model PostVM

@{
    ViewData["Title"] = "Upsert";
}

<div class="container">
    <div class="row">
        <h2 class="text-primary">@(Model.Post.Id != 0 ? "Update" : "Create") post</h2>
    </div>
    <hr />
    <div class="row ">
        <div class="col-8">
            <form asp-action="Upsert" enctype="multipart/form-data">
                <input asp-for="@Model.Post.Id" hidden />
                <input asp-for="@Model.Post.ImageUrl" hidden />
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="@Model.Post.Title" class="control-label"></label>
                    <input asp-for="@Model.Post.Title" class="form-control" />
                    <span asp-validation-for="@Model.Post.Title" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Post.Author" class="control-label"></label>
                    <input asp-for="@Model.Post.Author" class="form-control" />
                    <span asp-validation-for="@Model.Post.Author" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Post.Text" class="control-label"></label>
                    <textarea asp-for="@Model.Post.Text" class="form-control" rows="10"></textarea>
                    <span asp-validation-for="@Model.Post.Text" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Post.CategoryId" class="control-label"></label>
                    <select asp-for="@Model.Post.CategoryId" class="form-control" asp-items="@Model.CategoryList">
                        <option disabled selected>--Select Category</option>
                    </select>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Post.ImageUrl" class="control-label"></label>
                    <input type="file" name="file" class="form-control" />

                </div>
                <div class="row justify-content-evenly">
                    <div class="col-md-auto">
                        <button type="submit" class="btn btn-primary">@(Model.Post.Id != 0 ? "Update" : "Create")</button>
                    </div>
                    <div class="col-md-auto">
                        <a asp-action="Index" class="btn btn-primary">Back to List</a>
                    </div>
                </div>
            </form>
        </div>

        <div class="col-4">
            <img src="@Model.Post.ImageUrl" width="300" style="border-radius:5px; border: 1px solid #bbb9b9" />
        </div>
    </div>



</div>


@section Scripts{
    @{
    <partial name="_ValidationScriptsPartial" />
    }
}

NikitaBlog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NikitaBlog</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NikitaBlog.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">NikitaBlog</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Post" asp-action="Index">Posts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - NikitaBlog - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

NikitaBlog/Views/Shared/_Notification.cshtml
@if(TempData["success"] != null)
{
    <div class="row">
        <h5 class="text-primary">@TempData["success"]</h5>
    </div>
}